# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

#################################### Constants ####################################

  TEST_SIMULATORS = ['iPhone 14 Pro']
  TEST_DEVICES = [
    'platform=iOS,id=9a31ef5bf7216fa79ec31af3f29901c209175937',
    'platform=iOS,id=8a31ef5bf2216fa49ec31af3f29901c209075937'
  ]

################################## Helper Methods ##################################

  desc "Generate test reports"
  def generate_report
    puts "Generating Test Report ..."
    sh 'xchtmlreport -r test_output/Kalculator.xcresult'
    puts "Test Report Successfully generated"
  end



################################### Private Lanes ###################################

  desc "Execute tests on simulators"
  private_lane :parrallel_simulator_test do
      scan(
        scheme: 'Kalculator', # Project scheme name
        clean: true, # clean project folder before test execution
	#only_testing: "KalculatorUITests/NumberSelectTest/testSelectAllButtons",
        devices: TEST_SIMULATORS,
        result_bundle: "test_output/Kalculator.xcresult"
      )
      generate_report
  end

################################### Public Lanes ###################################

  desc "Execute tests on simulators with error handling"
  lane :simulator_test do
    begin
      parrallel_simulator_test
    rescue
      generate_report
    end
  end

 